name: Preview

on:
  workflow_run:
    workflows: ["Build and push container image"]
    branches: [postprint]
    types: [completed]

jobs:
  execute:
    uses: eds-book/notebooks-workflows/.github/workflows/preview.yaml@main